# Gems
plugings:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - certified
  - jekyll-email-protect

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ahmet Çelik
description:      'Everything is under control'
url:              https://github.com/celiktemha
baseurl:          /

author:
  name:           'Ahmet Çelik'
  url:            https://github.com/celiktemha

paginate:         5

# Custom vars
version:          2.1.0

encoding:         utf-8
github:
  repo:           https://github.com/celiktemha

kramdown:
 input: GFM
 syntax_highlighter: rouge
